<?php

namespace Gremio\ProveedoresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CajeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajeroRepository extends EntityRepository
{
}