<?php

namespace Gremio\ProveedoresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends EntityRepository
{
    public function getVigentes()
    {
        return $this
                ->createQueryBuilder('p')
                ->where('p.fecha_baja IS NULL');
    }
    
    public function findVigentes()
    {
        
        return $this->getEntityManager()
                ->createQuery("SELECT p FROM GremioProveedoresBundle:Proveedor p WHERE p.fecha_baja is null 
                    and (p.evento = ?1 or p.evento is null)")
                ->setParameter(1, false)
                ->getResult();
    
    }
    
    public function findEventos()
    {
        
        return $this->getEntityManager()
                ->createQuery("SELECT p FROM GremioProveedoresBundle:Proveedor p WHERE p.evento = ?1")
                ->setParameter(1, true)
                ->getResult();
    
    }
    
    public function findEventosVigentes()
    {
        
        return $this->getEntityManager()
                ->createQuery("SELECT p FROM GremioProveedoresBundle:Proveedor p WHERE p.evento = ?1 
                    AND p.fecha_vencimiento >= ?2 AND p.fecha_baja IS NULL")
                ->setParameter(1, true)
                ->setParameter(2, new \DateTime())
                ->getResult();
    
    }
}