<?php

namespace Gremio\ProveedoresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RubroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubroRepository extends EntityRepository
{
    public function getVigentes()
    {
        return $this
                ->createQueryBuilder('r')
                ->where('r.fecha_baja IS NULL');
    }
}