<?php

namespace Gremio\SociosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuotaEmisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuotaEmisionRepository extends EntityRepository
{
	public function findLotePeriodo($fechaLote,$reparticion){
		$em = $this->getEntityManager();
		$consulta = $em->createQuery('SELECT c FROM GremioSociosBundle:CuotaEmision c JOIN c.emision e JOIN e.socio s JOIN s.reparticion r 
                                      WHERE c.fecha_vencimiento <= :fechaLote
                                      AND (c.procesada = :falso
                                      or c.fecha_proceso IS NULL)
				                      AND r.id=:reparticion');
		$consulta->setParameter('fechaLote', $fechaLote);
		$consulta->setParameter('falso', false);
		//$consulta->setParameter('socio', $socio);
		$consulta->setParameter('reparticion', $reparticion);
		return $consulta->getResult();
		
		
	}
	
	public function findImportePeriodo($fechaLote,$reparticion){
		$em = $this->getEntityManager();
		$consulta = $em->createQuery('SELECT  sum(c.importe_cuota) from GremioSociosBundle:CuotaEmision c
				 join c.emision e join e.socio s JOIN s.reparticion r WHERE c.fecha_vencimiento <= :fechaLote 
				AND (c.procesada = :falso or c.fecha_proceso IS NULL) AND r.id=:reparticion');
		$consulta->setParameter('fechaLote', $fechaLote);
		$consulta->setParameter('falso', false);
		$consulta->setParameter('reparticion', $reparticion);
		return $consulta->getSingleScalarResult();
	}
}