<?php

namespace Gremio\SociosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoEmisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEmisionRepository extends EntityRepository
{
    public function findByNombre($nombre)
    {
    }
}