<?php

namespace Gremio\AbmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReparticionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparticionRepository extends EntityRepository
{
}